import { responseSymbol } from 'next/dist/server/web/spec-compliant/fetch-event';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import Nav from '../../components/Nav/Nav';
import DefaultLayout from '../../layout/default';

export default function Cat() {
	const router = useRouter();
	const { id } = router.query;

	const [cat, setCat] = useState(null);

	useEffect(() => {
		fetchCat();
	}, []);

	// get cat info
	const fetchCat = async () => {
		try {
			console.log(router.query);
			console.log(id);
			const response = await fetch(`/api/cats/${id}`);
			const data = await response.json();
			console.log(data);
			setCat(data);
		} catch (error) {}
	};

	return (
		<>
			<Head>
				<title>Cats {cat && cat.name}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<DefaultLayout>
				{cat && (
					<div className='container mt-5' style={{ display: 'flex' }}>
						<div className='mx-5'>
							<img src={cat && cat.image && cat.image.url} />
							<h1>{cat.name}</h1>
							<p>{cat.description} </p>
						</div>
					</div>
				)}
			</DefaultLayout>
		</>
	);
}
