import Head from 'next/head';
import Image from 'next/image';
import Jumbotron from '../components/Jumbotron/Jumbotron';
import Nav from '../components/Nav/Nav';
import DefaultLayout from '../layout/default';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<>
			<div className='container'>
				<Head>
					<title>Create Next App</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>

				<DefaultLayout>
					<Jumbotron />

					<main>Hello</main>
				</DefaultLayout>
			</div>
		</>
	);
}
